# Generated by Django 5.2.8 on 2025-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Код верификации"
            ),
        ),
    ]
