# Generated by Django 5.2.8 on 2025-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0002_tguser_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Код верификации",
            ),
        ),
    ]
